version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8    
  pre_build:
    commands:
      - echo installing angular dependencies...
      - echo $PWD
      - ls
      - cd ui/MorganizerUI
      - echo $PWD
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building angular application...
      - echo $PWD
      - ls      
      - ng build --prod
      - echo building maven project      
      - cd ../..
      - cd api/MorganizerAPI
      - mvn clean install      
      - mv ./target ../..
      - cd ../..
  post_build:
    commands:
      - echo moving files to s3 
      - echo $PWD
      - aws s3 sync ./ui/MorganizerUI/dist/MorganizerUI s3://morganized-ui --acl 'public-read' --delete
artifacts:
  files:
    - target/*.jar
  discard-paths: yes