version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8    
  pre_build:
    commands:
      - echo installing angular dependencies...
      - echo $PWD
      - ls
      - cd ui/MorganizerUI
      - echo $PWD
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building angular application...
      - echo $PWD
      - ls      
      - ng build --prod
      - echo building maven project      
      - cd ../..
      - cd api/MorganizerAPI
      - mvn clean install            
      - cd ../..      
  post_build:
    commands:
      - echo moving files to s3 
      - echo $PWD       
      - aws s3 sync ./ui/MorganizerUI/dist/MorganizerUI s3://morganized-ui --acl 'public-read' --delete
      # - mkdir target
      - ls ./api/MorganizerAPI/target
      - mv ./api/MorganizerAPI/target ./
      # - aws s3 sync ./api/MorganizerAPI/target s3://elasticbeanstalk-us-east-2-094219252891
artifacts:
  files: 
    - target/morganizerAPI-0.0.1-SNAPSHOT.jar



